spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        web:
          filter: DEBUG

refreshKey: sdfhajks1u8924371389
secretKey: sdjhfklashjf8927431892jnjksdah

---

spring:
  config:
    activate:
      on-profile: "prod"