spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
# create  :  ?? ???? ???? ?? ?? [ DROP + CREATE ]
# create-drop  :  CREATE ??? ??? ??????? ??? ? ??? DDL? ??  [ DROP + CREATE + DROP ]
# update  :  DB ???? ??? ?? ??? ???? ?? ??? ?? [ ???? ?? ?? CREATE ]
# validate  :  DB ???? ??? ????? ???? ??? ??? ??? ??? ??????? ???? ??
# none  :  ?? ?? ??? ???? ??

---

spring:
  config:
    activate:
      on-profile: "prod"

server.ssl.key-store: keystore.p12
server.ssl.key-store-password: ENC(0bK1+y9RglKiVtVsGYjTnKWrnWqSr/Ke)
server.ssl.keyStoreType: PKCS12
